# Generated by Django 5.2.8 on 2026-01-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_commented_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='number_comments',
            field=models.FloatField(default=0),
        ),
    ]
