# Generated by Django 5.2.8 on 2026-01-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_author_alter_comment_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='number_comments',
        ),
    ]
